version: '3.9'

services:
  postgres_db:
    image: postgres:15.3-bullseye
    container_name: postgres_db
    restart: always
    env_file:
      - docker.env
    ports:
      - "5433:5433"
    volumes:
      - ~/postgres_data:/var/lib/postgresql/data
      
  nestjs-api:
    image: nestjs-api
    container_name: nestjs-api
    env_file:
      - .env
    ports:
      - "7777:7777"
    volumes:
      - ~/uploads:/user/src/app/uploads
    depends_on:
      - postgres_db


volumes:
    postgres_data: