version: '3.9'


      
  nestjs-api:
    image: nestjs-api
    container_name: nestjs-api
    env_file:
      - .env
    ports:
      - "7777:7777"
    volumes:
      - ~/uploads:/user/src/app/uploads
    depends_on:
      - postgres_db


volumes:
    postgres_data:
